# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: de2be5fa14541678961916993030c2d646c7b6ef046c560f8772fe6a1f32455ce1f5bdfc05a395202e60e82cf0876c5945a094cd415903ef37a7d77583568693

test:
  secret_key_base: f6d05927f017852a2e92bf50a9a4875142b0e8f563bc3b9b290a7cd3f6114a8af49219dcac24e01c7c3b9ca933d7caced2df3b7dc35c97c9fa91ef1c70e9f5fd

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
